spring.application.name=Revpay1

# Server Configuration
server.port=8099

# Database Configuration (Oracle FreeSQL DB)
spring.datasource.url=jdbc:oracle:thin:@//db.freesql.com:1521/23ai_34ui2
spring.datasource.username=ASHIVATEJA2208_SCHEMA_J1A0D
spring.datasource.password=S79VBHXZJMpJH657HZLP01$ZJG45ZH
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Disable security by default to ease testing initially (will configure API later)
spring.security.user.name=admin
spring.security.user.password=admin

# Security Debugging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=revpay.demo@gmail.com
spring.mail.password=placeholder_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
