spring.application.name=Revpay1

# Server Configuration
server.port=8080
server.servlet.context-path=/pay

# Profile Configuration
spring.profiles.active=dev

# Database Configuration (Oracle FreeSQL DB)
spring.datasource.url=jdbc:oracle:thin:@db.freesql.com:1521/23ai_34ui2
spring.datasource.username=ASHIVATEJA2208_SCHEMA_J1A0D
spring.datasource.password=GP9S1ZGS5DPNfAAXM4770D8EB5Y!1E
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Disable security by default to ease testing initially (will configure API later)
spring.security.user.name=admin
spring.security.user.password=admin
